# Generated by Django 5.2.1 on 2025-05-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(blank=True, max_length=20)),
                ('platform', models.CharField(max_length=50)),
                ('retries', models.IntegerField(default=0)),
            ],
        ),
    ]
