# Generated by Django 5.2.1 on 2025-06-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_title_alter_task_end_time_alter_task_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='System Update', max_length=100),
        ),
    ]
